### ISSUE TITLE
how do you specify the domain/subdomain for the nginx configuration?

### ISSUE THREAD

**Issue by vesper8** [kaizendorks/vue-cli-plugin-vuedock#10]
Hi there! I've started using your vue-cli plugin and am fairly new to Docker. I have it working now with Gitlab DR and Jenkins CI and the files generated through this plugin have made it easy to deploy and get a docker working in production

However I can't figure out how to specify a domain/subdomain for the nginx to map to. Specifically, I am running multiple docker containers each with their own vue-cli web apps inside on the same VPS. I've pointed multiple domains/subdomains to point to the VPS's IP but don't know how to tell the nginx inside the different docker containers to map accordingly to the different domains/subdomains

I hope I am explaining myself properly.. can you help me understand what I need to do? Do I need to run the docker image with a special parameter to configure the nginx config? Or should it be part of the dockerfile when building the image with my build server?

Thanks a lot!

**Comment by iorubs** [comment]
Hi Vesper,

Very glad to hear that you found the plugin useful :)

The current Prod image uses Nginx for serving an individual app (lets call it app container), the easiest way would be to use an extra proxy (maybe nginx) for routing to all the individual app containers. 

Another really cool one is traeki (https://traefik.io/), it integrates with both Swarm and Kubernetes so it auto-configures itself when you deploy new apps.

Hope this is of some help.

**Comment by iorubs** [comment]
Going to close this issue, feel free to reopen a new one if needed.

**Comment by iorubs** [comment]
Going to close this issue, feel free to reopen a new one if needed.
